from __future__ import annotations

from typing import Any

from quant_os.research.social_intake.social_capture_models import SOCIAL_INTAKE_SAFETY


def build_autonomy_milestones() -> dict[str, Any]:
    milestones = [
        _milestone(
            1,
            "research_intake_autonomous",
            "Research intake autonomous",
            "MET",
            [],
            "sequence35_intake_run",
            "run governed local/cached intake daily",
            "Phase 35",
        ),
        _milestone(
            2,
            "evidence_acquisition_repeatable",
            "Evidence acquisition repeatable",
            "IN_PROGRESS",
            ["BLOCKED_BY_THIN_EVIDENCE", "SHADOW_EVIDENCE_TOO_THIN"],
            "sequence35_evidence_bridge",
            "add approved read-only data fixtures that feed replay windows",
            "Phase 36",
        ),
        _milestone(
            3,
            "replay_inputs_sufficient",
            "Replay inputs sufficient",
            "BLOCKED",
            ["REPLAY_INPUT_INSUFFICIENT"],
            "sequence28_replay_inputs",
            "expand timestamped replay inputs with real cached windows",
            "Phase 36",
        ),
        _milestone(
            4,
            "shadow_decisions_generated",
            "Shadow decisions generated",
            "MET",
            [],
            "sequence31_shadow_execution",
            "keep shadow policy deterministic and blocked when weak",
            "Phase 31",
        ),
        _milestone(
            5,
            "shadow_proving_threshold_met",
            "Shadow proving threshold met",
            "BLOCKED",
            ["SHADOW_PROVING_TOO_THIN"],
            "sequence32_shadow_proving",
            "accumulate enough replay windows to evaluate stability",
            "Phase 36",
        ),
        _milestone(
            6,
            "bounded_shadow_rehearsal_ready",
            "Bounded shadow rehearsal ready",
            "BLOCKED",
            ["SHADOW_EVIDENCE_TOO_THIN"],
            "sequence33_shadow_rehearsal",
            "prove blockers are understood across windows",
            "Phase 37",
        ),
        _milestone(
            7,
            "dry_run_parity_ready",
            "Dry-run parity ready",
            "BLOCKED",
            ["NO_DRY_RUN_PARITY_PROTOCOL"],
            "canary_preflight_reports",
            "define deterministic dry-run parity protocol",
            "Phase 38",
        ),
        _milestone(
            8,
            "canary_preconditions_met",
            "Canary preconditions met",
            "BLOCKED",
            ["CANARY_PRECONDITIONS_NOT_MET"],
            "sequence32_canary_preconditions",
            "satisfy fail-closed canary checklist with proof",
            "Phase 39",
        ),
        _milestone(
            9,
            "manual_arming_protocol_present",
            "Manual arming protocol present",
            "BLOCKED",
            ["NO_MANUAL_ARMING_PROTOCOL"],
            "canary_arm_token_reports",
            "write operator-supervised arming and disarming procedure",
            "Phase 39",
        ),
        _milestone(
            10,
            "first_tiny_canary_allowed",
            "First tiny canary allowed",
            "BLOCKED",
            ["LIVE_DEFAULT_OFF", "CANARY_NOT_EARNED"],
            "live_canary_reports",
            "allow only after milestones 1-9 are met",
            "Future canary phase",
        ),
        _milestone(
            11,
            "real_canary_reconciliation_passed",
            "Real canary reconciliation passed",
            "BLOCKED",
            ["NO_REAL_CANARY_RECONCILIATION"],
            "live_reconciliation_reports",
            "reconcile every real canary event deterministically",
            "Future canary phase",
        ),
        _milestone(
            12,
            "expansion_blocked_until_repeated_proof",
            "Expansion still blocked until repeated proof",
            "BLOCKED",
            ["REPEATED_PROOF_REQUIRED"],
            "capital_ladder_reports",
            "require repeated canary proof before any expansion",
            "Future expansion phase",
        ),
    ]
    next_required = next(item for item in milestones if item["status"] != "MET")
    return {
        "schema_version": "autonomy_milestones_v1",
        "sequence": "35",
        "ledger_status": "FINITE_AUTONOMY_PATH_EXPLICIT",
        "milestone_count": len(milestones),
        "milestones": milestones,
        "next_required_milestone": next_required,
        "live_orders_allowed": False,
        **SOCIAL_INTAKE_SAFETY,
        "live_allowed": False,
        "live_promotion_status": "LIVE_BLOCKED",
        "evidence_only": True,
    }


def _milestone(
    index: int,
    milestone_id: str,
    title: str,
    status: str,
    blockers: list[str],
    evidence_source: str,
    required_next_action: str,
    phase_likely_responsible: str,
) -> dict[str, Any]:
    return {
        "milestone_index": index,
        "milestone_id": milestone_id,
        "title": title,
        "status": status,
        "current_blockers": blockers,
        "evidence_source": evidence_source,
        "required_next_action": required_next_action,
        "phase_likely_responsible": phase_likely_responsible,
        "required_for_live_orders": True,
    }
